import Head from "next/head";
import MapboxMap from "@/components/MapboxMap";
import NewMapboxMap from "@/components/NewMapboxMap";
import MainNavbar from "@/components/MainNavbar";
import { Button, Container, Navbar, Text, Spacer } from "@nextui-org/react";
import "mapbox-gl/dist/mapbox-gl.css";
//import "./styles/Home.module.css";
import { useEffect, useRef, useState } from "react";
import { Switch, useTheme } from '@nextui-org/react';
import axios from 'axios';
import {baseApiUrl, getCsrfToken} from '@/api/Utils';
import { get } from "http";

export default function Feed() {
  
  const [testMessage, setTestMessage] = useState("Hello World");

    useEffect(() => {
      // axios.get('http://127.0.0.1:8000/message/get_message/')
      //   .then(response => {
      //     console.log(response.data);
      //     setTestMessage(response.data.message[0].mid);
      //   })
      //   .catch(error => {
      //     console.log(error);
      //   });
      // let csrftoken = getCsrfToken();
      // console.log(csrftoken);
      axios.post(baseApiUrl + '/message/post_message/',
        {
          "content": "Hello from NextJS"
        },
        {
          headers: {
            'x-csrftoken': getCsrfToken(),
          },
          withCredentials: true
        }
      ).then(response => {
          console.log(response.data);
          // setTestMessage(response.data);
        }).catch(error => {
          console.log(error);
        }
      )
    }, []);

  return (
    <>
      <Head>
        <title>Map | NeighborNet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text h1>{testMessage}</Text>
      <main>
        <NewMapboxMap />
      </main>
    </>
  );
}

