import React from "react";
import Head from "next/head";
import { Button, Container, Navbar, Text, Spacer } from "@nextui-org/react";
import axios from "axios";
import { baseApiUrl, getCsrfToken } from "@/api/Utils";
import RelaCard from "@/components/RelaCard";

interface Friend {
  id: string;
  username: string;
  avatar?: string;
}

interface Neighbor {
  id: string;
  username: string;
  avatar?: string;
}

export default function Rela() {
  const [friends, setFriends] = React.useState<Friend[]>([]);
  const [neighbors, setNeighbors] = React.useState<Neighbor[]>([]);

  function getFriends() {
    axios.get(baseApiUrl + "/userrela/friends").then((response) => {
      console.log(response.data);
      const friends: Friend[] = [];
      for (let i = 0; i < response.data.friends.length; i++) {
        const friend: Friend = {
          id: response.data.friends[i].id,
          username: response.data.friends[i].username,
          avatar: response.data.friends[i].image_url,
        };
        friends.push(friend);
      }
      setFriends(friends);
    });
  }

  function getNeighbors() {
    axios.get(baseApiUrl + "/userrela/neighbors").then((response) => {
      console.log(response.data);
      const neighbors: Neighbor[] = [];
      for (let i = 0; i < response.data.neighbors.length; i++) {
        const neighbor: Neighbor = {
          id: response.data.neighbors[i].id,
          username: response.data.neighbors[i].username,
          avatar: response.data.neighbors[i].image_url,
        };
        neighbors.push(neighbor);
      }
      setNeighbors(neighbors);
    });
  }

  React.useEffect(() => {
    getFriends();
    getNeighbors();
  }, []);

  return (
    <>
      <Head>
        <title>Map | NeighborNet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Spacer y={1} />
        <Container sm>
          <Text h2>Your Friends</Text>
          <RelaCard rela={friends} />
        </Container>
        <Container sm>
          <Text h2>Your Follow Neighbors</Text>
          <RelaCard rela={neighbors} />
        </Container>
      </main>
    </>
  );
}
